//! Policy serialization and deserialization.

use super::{FsPermission, Policy};
use crate::policy::PolicyError;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

impl Policy {
    /// Load policy from a TOML file.
    pub fn from_file(path: &PathBuf) -> Result<Self, PolicyError> {
        let contents = fs::read_to_string(path)
            .map_err(|e| PolicyError::FileError(path.clone(), e.to_string()))?;
        Self::from_toml(&contents)
    }

    /// Parse policy from TOML string.
    pub fn from_toml(toml: &str) -> Result<Self, PolicyError> {
        let policy: Policy =
            toml::from_str(toml).map_err(|e| PolicyError::ParseError(e.to_string()))?;

        policy.validate()?;

        Ok(policy)
    }

    /// Serialize policy to human-readable TOML.
    pub fn to_toml(&self) -> Result<String, PolicyError> {
        let mut output = String::new();

        output.push_str("# Cerberus Policy Configuration\n");
        output.push_str("# Generated by: cerberus\n");
        output.push_str("#\n");
        output.push_str("# This file configures the sandbox security policy.\n");
        output.push_str("# Edit values below to customize isolation behavior.\n");
        output.push('\n');

        output.push_str("# Network Access (matches namespaces.network directly)\n");
        output.push_str("# allow_network = true  -> namespaces.network = true\n");
        output.push_str("# allow_network = false -> namespaces.network = false\n");
        output.push_str(&format!(
            "# Current: allow_network = {}\n\n",
            self.allow_network()
        ));

        output.push_str("# Isolation Fallback Options\n");
        output.push_str(
            "# These flags only relax Landlock and mount-isolation downgrade behavior.\n",
        );
        output.push_str(
            "# They do not bypass namespace requirements or enabled network_policy gating.\n",
        );
        output
            .push_str("# landlock_optional = true allows execution when Landlock is unavailable\n");
        output.push_str(&format!(
            "landlock_optional = {}    # true = continue without Landlock, false = fail if unavailable\n",
            self.landlock_optional
        ));
        output.push_str(
            "# mount_isolation_fallback = true allows fallback to mount-only isolation\n",
        );
        output.push_str(&format!(
            "mount_isolation_fallback = {}    # true = use mount fallback, false = no fallback\n\n",
            self.mount_isolation_fallback
        ));

        output.push_str("# Custom Filesystem Rules\n");
        output.push_str("# Add paths beyond the predefined groups above.\n");
        output.push_str("#\n");
        output.push_str("# [[custom_paths]]\n");
        output.push_str("# path = \"/your/custom/path\"\n");
        output.push_str(
            "# permission = \"readonly\" | \"readwrite\" | \"readexecute\" | \"readwriteexecute\"\n",
        );
        output.push_str("#\n");
        output.push_str("# Permissions:\n");
        output.push_str("#   readonly     = can read files, cannot write or execute\n");
        output.push_str(
            "#   readwrite    = can read, write, create, replace, and delete files, cannot execute\n",
        );
        output.push_str("#   readexecute  = can read and execute files, cannot write\n");
        output.push_str(
            "#   readwriteexecute = can read, write, create, replace, delete, and execute files\n",
        );
        if self.custom_paths.is_empty() {
            output.push_str("custom_paths = []\n\n");
        } else {
            for rule in &self.custom_paths {
                let perm = match &rule.permission {
                    FsPermission::ReadOnly => "readonly",
                    FsPermission::ReadWrite => "readwrite",
                    FsPermission::ReadExecute => "readexecute",
                    FsPermission::ReadWriteExecute => "readwriteexecute",
                };
                output.push_str("[[custom_paths]]\n");
                output.push_str(&format!("path = \"{}\"\n", rule.path.display()));
                output.push_str(&format!("permission = \"{}\"\n\n", perm));
            }
        }

        output.push_str("# Path Groups - Toggle Predefined Filesystem Access\n");
        output.push_str("# true  = ALLOW access to these paths\n");
        output.push_str("# false = BLOCK access to these paths\n");
        output.push_str("#\n");
        output.push_str("[path_groups]\n");
        output.push_str("# /usr/bin - System executables (ls, cat, python, etc.)\n");
        output.push_str(&format!(
            "system_binaries = {}    # true = read+execute, false = blocked\n",
            self.path_groups.system_binaries
        ));
        output.push_str("# /usr/lib, /lib, /lib64 - Shared libraries (.so files)\n");
        output.push_str(&format!(
            "system_libraries = {}   # true = read+execute, false = blocked\n",
            self.path_groups.system_libraries
        ));
        output.push_str("# /tmp - Temporary files directory\n");
        output.push_str(&format!(
            "temp_directories = {}   # true = read+write, false = blocked\n",
            self.path_groups.temp_directories
        ));
        output.push_str("# /dev - Device files (null, zero, random, tty, etc.)\n");
        output.push_str(&format!(
            "device_files = {}       # true = read+write, false = blocked\n",
            self.path_groups.device_files
        ));
        output.push_str("# /proc - Process information filesystem\n");
        output.push_str(&format!(
            "proc_filesystem = {}    # true = read-only, false = blocked\n",
            self.path_groups.proc_filesystem
        ));
        output.push_str("# /mnt/wsl - WSL-specific files (resolv.conf symlink target)\n");
        output.push_str(&format!(
            "wsl_paths = {}          # true = read-only, false = blocked\n\n",
            self.path_groups.wsl_paths
        ));

        output.push_str("# Namespace Configuration\n");
        output.push_str("# mount, pid, and user keep their direct isolation meaning.\n");
        output.push_str("# network uses positive public semantics: true = allow network, false = block network.\n");
        output.push_str("#\n");
        output.push_str("[namespaces]\n");
        output.push_str("# mount = Filesystem mount points isolated from host\n");
        output.push_str(&format!(
            "mount = {}    # true = isolated, false = shared with host\n",
            self.namespaces.mount
        ));
        output.push_str("# pid = Process IDs isolated (cannot see host processes)\n");
        output.push_str(&format!(
            "pid = {}      # true = isolated, false = can see host processes\n",
            self.namespaces.pid
        ));
        output.push_str("# network = Whether network access is allowed\n");
        output.push_str("# true = network allowed, false = network blocked\n");
        output.push_str(&format!(
            "network = {}  # true = network allowed, false = network blocked\n",
            self.namespaces.network
        ));
        output.push_str("# user = User/group IDs isolated (unprivileged operation)\n");
        output.push_str("# NOTE: user is independent from network semantics. Choose the combination your runtime supports.\n");
        output.push_str(&format!(
            "user = {}     # true = isolated (unprivileged), false = real UID/GID\n\n",
            self.namespaces.user
        ));

        output.push_str("# Resource Limits\n");
        output.push_str("[resources]\n");
        output.push_str("# Maximum execution time in seconds (process killed if exceeded)\n");
        output.push_str(&format!("timeout_secs = {}\n", self.resources.timeout_secs));
        output.push_str("# Maximum memory in bytes (process fails allocation if exceeded)\n");
        output.push_str(
            "# Omit this field or set to a positive value for a limit (unlimited if omitted)\n",
        );
        match self.resources.max_memory_bytes {
            Some(mem) if mem > 0 => output.push_str(&format!(
                "max_memory_bytes = {}    # {} MB\n",
                mem,
                mem / 1024 / 1024
            )),
            _ => {} // Omit field for unlimited (None or normalized 0)
        }
        output.push_str("# Maximum number of processes (prevents fork bombs)\n");
        output.push_str(
            "# Omit this field or set to a positive value for a limit (unlimited if omitted)\n",
        );
        match self.resources.max_processes {
            Some(procs) if procs > 0 => output.push_str(&format!("max_processes = {}\n", procs)),
            _ => {} // Omit field for unlimited (None or normalized 0)
        }
        output.push('\n');

        output.push_str("# Environment Variables\n");
        output.push_str("# Only listed variables are passed to the sandboxed process.\n");
        output.push_str("# Common values: PATH, LANG, HOME, USER, TERM\n");
        output.push_str("[environment]\n");
        output.push_str(&format!("whitelist = {:?}\n", self.environment.whitelist));

        Ok(output)
    }

    /// Write policy to a TOML file.
    pub fn to_file(&self, path: &PathBuf) -> Result<(), PolicyError> {
        let toml = self.to_toml()?;
        let mut file = fs::File::create(path)
            .map_err(|e| PolicyError::FileError(path.clone(), e.to_string()))?;
        file.write_all(toml.as_bytes())
            .map_err(|e| PolicyError::FileError(path.clone(), e.to_string()))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::{NetworkAction, NetworkPolicy, NetworkPolicyMode, NetworkRule};

    #[test]
    fn test_parse_toml_rejects_removed_network_config_field() {
        let toml = r#"
[path_groups]
network_config = true
"#;

        let error = Policy::from_toml(toml).unwrap_err();
        let message = error.to_string();

        assert!(message.contains("unknown field"));
        assert!(message.contains("network_config"));
    }

    #[test]
    fn test_parse_toml_with_read_write_execute_permission() {
        let toml = r#"
[[custom_paths]]
path = "/workspace/bin"
permission = "readwriteexecute"
"#;

        let policy = Policy::from_toml(toml).unwrap();
        let rule = policy.custom_paths.first().unwrap();

        assert_eq!(rule.path, PathBuf::from("/workspace/bin"));
        assert_eq!(rule.permission, FsPermission::ReadWriteExecute);
    }

    #[test]
    fn test_from_toml_with_invalid_network_policy() {
        let toml = r#"
[path_groups]
system_binaries = true

[namespaces]
network = true

[network_policy]
enabled = true

[[network_policy.rules]]
action = "allow"
cidrs = ["192.168.1.0/33"]
"#;
        let result = Policy::from_toml(toml);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("Validation error"));
    }

    #[test]
    fn test_from_toml_rejects_network_policy_when_network_is_blocked() {
        let toml = r#"
[namespaces]
network = false

[network_policy]
enabled = true
mode = "monitor"
"#;

        let result = Policy::from_toml(toml);

        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("network_policy cannot be configured when namespaces.network = false"));
    }

    #[test]
    fn test_from_toml_accepts_disabled_network_policy_when_network_is_blocked() {
        let toml = r#"
[namespaces]
network = false

[network_policy]
enabled = false
mode = "monitor"
"#;

        let policy = Policy::from_toml(toml).unwrap();

        assert!(!policy.allow_network());
        assert!(policy.network_policy.is_some());
        assert!(!policy.network_policy.as_ref().unwrap().enabled);
    }

    #[test]
    fn test_example_policies_parse_correctly() {
        let examples = [
            (
                "high-security-agent",
                include_str!("../../../../../config/cerberus-policies/high-security-agent.toml"),
            ),
            (
                "repo-root-write-network-off",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-write-network-off.toml"
                ),
            ),
            (
                "repo-root-write-network-on",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-write-network-on.toml"
                ),
            ),
            (
                "repo-root-write-network-on-dev-env",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-write-network-on-dev-env.toml"
                ),
            ),
            (
                "repo-root-python-network-filtered",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-python-network-filtered.toml"
                ),
            ),
            (
                "minimal-example",
                include_str!("../../../../../config/cerberus-policies/minimal-example.toml"),
            ),
            (
                "llm-safe-example",
                include_str!("../../../../../config/cerberus-policies/llm-safe-example.toml"),
            ),
            (
                "process-visible-example",
                include_str!(
                    "../../../../../config/cerberus-policies/process-visible-example.toml"
                ),
            ),
            (
                "strict-example",
                include_str!("../../../../../config/cerberus-policies/strict-example.toml"),
            ),
        ];

        for (name, toml_content) in examples {
            let policy = Policy::from_toml(toml_content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {}", name, e));

            let roundtrip = Policy::from_toml(&policy.to_toml().unwrap())
                .unwrap_or_else(|e| panic!("Failed to roundtrip {}: {}", name, e));

            assert_eq!(
                policy.landlock_optional, roundtrip.landlock_optional,
                "landlock_optional mismatch for {}",
                name
            );
            assert_eq!(
                policy.mount_isolation_fallback, roundtrip.mount_isolation_fallback,
                "mount_isolation_fallback mismatch for {}",
                name
            );
            assert_eq!(
                policy.custom_paths.len(),
                roundtrip.custom_paths.len(),
                "custom_paths length mismatch for {}",
                name
            );
            assert_eq!(
                policy
                    .custom_paths
                    .iter()
                    .map(|rule| (&rule.path, &rule.permission))
                    .collect::<Vec<_>>(),
                roundtrip
                    .custom_paths
                    .iter()
                    .map(|rule| (&rule.path, &rule.permission))
                    .collect::<Vec<_>>(),
                "custom_paths mismatch for {}",
                name
            );
        }
    }

    #[test]
    fn test_example_policies_lock_intended_network_semantics() {
        let examples = [
            (
                "high-security-agent",
                include_str!("../../../../../config/cerberus-policies/high-security-agent.toml"),
                false,
                false,
                true,
            ),
            (
                "repo-root-write-network-off",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-write-network-off.toml"
                ),
                false,
                false,
                true,
            ),
            (
                "repo-root-write-network-on",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-write-network-on.toml"
                ),
                true,
                true,
                false,
            ),
            (
                "repo-root-write-network-on-dev-env",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-write-network-on-dev-env.toml"
                ),
                true,
                true,
                false,
            ),
            (
                "repo-root-python-network-filtered",
                include_str!(
                    "../../../../../config/cerberus-policies/repo-root-python-network-filtered.toml"
                ),
                true,
                true,
                false,
            ),
            (
                "minimal-example",
                include_str!("../../../../../config/cerberus-policies/minimal-example.toml"),
                true,
                true,
                false,
            ),
            (
                "llm-safe-example",
                include_str!("../../../../../config/cerberus-policies/llm-safe-example.toml"),
                true,
                true,
                false,
            ),
            (
                "process-visible-example",
                include_str!(
                    "../../../../../config/cerberus-policies/process-visible-example.toml"
                ),
                true,
                true,
                false,
            ),
            (
                "strict-example",
                include_str!("../../../../../config/cerberus-policies/strict-example.toml"),
                false,
                false,
                true,
            ),
        ];

        for (name, toml_content, expected_allow_network, expected_public_network, expected_user) in
            examples
        {
            let policy = Policy::from_toml(toml_content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {}", name, e));

            assert_eq!(
                policy.allow_network(),
                expected_allow_network,
                "allow_network mismatch for {}",
                name
            );
            assert_eq!(
                policy.namespaces.network, expected_public_network,
                "namespaces.network mismatch for {}",
                name
            );
            assert_eq!(
                policy.namespaces.user, expected_user,
                "user namespace mismatch for {}",
                name
            );
        }
    }

    #[test]
    fn test_example_policies_with_unlimited_resources_roundtrip_safely() {
        let examples = [
            (
                "minimal-example",
                include_str!("../../../../../config/cerberus-policies/minimal-example.toml"),
            ),
            (
                "process-visible-example",
                include_str!(
                    "../../../../../config/cerberus-policies/process-visible-example.toml"
                ),
            ),
        ];

        for (name, toml_content) in examples {
            let policy = Policy::from_toml(toml_content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {}", name, e));
            assert_eq!(
                policy.resources.max_processes, None,
                "{} should keep max_processes unlimited when omitted",
                name
            );

            let roundtrip_toml = policy.to_toml().unwrap();
            assert!(
                !roundtrip_toml.contains("max_processes = 0"),
                "{} should not serialize unlimited max_processes as 0",
                name
            );

            let roundtrip = Policy::from_toml(&roundtrip_toml)
                .unwrap_or_else(|e| panic!("Failed to roundtrip {}: {}", name, e));
            assert_eq!(
                roundtrip.resources.max_processes, None,
                "{} should keep unlimited max_processes after roundtrip",
                name
            );
        }
    }

    #[test]
    fn test_unlimited_resources_roundtrip_safely() {
        let mut policy = Policy::strict();
        policy.resources.max_memory_bytes = None;
        policy.resources.max_processes = None;

        let toml = policy.to_toml().unwrap();
        assert!(
            !toml.contains("max_memory_bytes = 0"),
            "TOML should not contain 'max_memory_bytes = 0' for unlimited"
        );
        assert!(
            !toml.contains("max_processes = 0"),
            "TOML should not contain 'max_processes = 0' for unlimited"
        );

        let restored = Policy::from_toml(&toml).unwrap();
        assert_eq!(
            restored.resources.max_memory_bytes, None,
            "Unlimited memory should round-trip as None"
        );
        assert_eq!(
            restored.resources.max_processes, None,
            "Unlimited processes should round-trip as None"
        );
    }

    #[test]
    fn test_validate_rejects_network_policy_when_public_network_is_blocked() {
        let mut policy = Policy::strict();
        policy.network_policy = Some(NetworkPolicy {
            enabled: true,
            mode: Some(NetworkPolicyMode::Monitor),
            default_action: Some(NetworkAction::Deny),
            rules: vec![NetworkRule {
                action: NetworkAction::Allow,
                direction: Some("outbound".to_string()),
                protocol: Some("tcp".to_string()),
                hosts: vec!["example.com".to_string()],
                cidrs: Vec::new(),
                ports: vec![(443, 443)],
            }],
        });

        let error = policy.validate().unwrap_err();
        assert!(error
            .to_string()
            .contains("network_policy cannot be configured when namespaces.network = false"));
    }

    #[test]
    fn test_validate_accepts_disabled_network_policy_when_public_network_is_blocked() {
        let mut policy = Policy::strict();
        policy.network_policy = Some(NetworkPolicy {
            enabled: false,
            mode: Some(NetworkPolicyMode::Monitor),
            default_action: Some(NetworkAction::Deny),
            rules: vec![NetworkRule {
                action: NetworkAction::Allow,
                direction: Some("outbound".to_string()),
                protocol: Some("tcp".to_string()),
                hosts: vec!["example.com".to_string()],
                cidrs: Vec::new(),
                ports: vec![(443, 443)],
            }],
        });

        assert!(policy.validate().is_ok());
    }

    #[test]
    fn test_explicit_zero_resources_normalized_to_none() {
        let toml = r#"
[path_groups]
system_binaries = true

[namespaces]
network = false

[resources]
timeout_secs = 30
max_memory_bytes = 0
max_processes = 0
"#;
        let policy = Policy::from_toml(toml).unwrap();
        assert_eq!(
            policy.resources.max_memory_bytes, None,
            "Explicit 0 should be normalized to None"
        );
        assert_eq!(
            policy.resources.max_processes, None,
            "Explicit 0 should be normalized to None"
        );
    }

    #[test]
    fn test_positive_resource_limits_preserved() {
        let mut policy = Policy::strict();
        policy.resources.max_memory_bytes = Some(512 * 1024 * 1024);
        policy.resources.max_processes = Some(100);

        let toml = policy.to_toml().unwrap();
        let restored = Policy::from_toml(&toml).unwrap();

        assert_eq!(
            restored.resources.max_memory_bytes,
            Some(512 * 1024 * 1024),
            "Positive memory limit should be preserved"
        );
        assert_eq!(
            restored.resources.max_processes,
            Some(100),
            "Positive process limit should be preserved"
        );
    }
}
