use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum InteractionSource {
    System, // framework generated interaction with user
    Tool {
        tool_name: String,
    }, // interaction generated by a tool execution
    Hooker {
        hooker_name: String,
        hook_point: String,
    }, // interaction generated by a hooker
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InteractionRequest {
    Confirm {
        prompt: String,
        source: Option<InteractionSource>,
    },
    TextInput {
        prompt: String,
        source: Option<InteractionSource>,
        #[serde(default)]
        is_secret: bool,
    },
    Choice {
        prompt: String,
        options: Vec<String>,
        allow_custom_input: bool,
        source: Option<InteractionSource>,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InteractionResponse {
    Confirmed {
        allowed: bool,
    },
    /// No user answer was received (turn cancelled, channel closed,
    /// timeout, or no interaction backend). Not an explicit denial.
    Unanswered,
    Text {
        value: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        display_value: Option<String>,
    },
    Choice {
        value: Option<String>,
    },
}

impl InteractionResponse {
    /// Response for a request whose interaction will never receive a real
    /// answer (turn cancelled while a tool waited on `ask`, prompt channel
    /// closed, no interaction backend available): `Confirm` is reported as
    /// `Unanswered` and `TextInput` / `Choice` carry no value, so the
    /// pending tool call can record a result and wind down instead of
    /// blocking forever. Distinct from timeout-style responses, which
    /// carry a sentinel value explaining the timeout to the model.
    pub fn unanswered(request: &InteractionRequest) -> Self {
        match request {
            InteractionRequest::Confirm { .. } => InteractionResponse::Unanswered,
            InteractionRequest::TextInput { .. } => InteractionResponse::Text {
                value: None,
                display_value: None,
            },
            InteractionRequest::Choice { .. } => InteractionResponse::Choice { value: None },
        }
    }
}

#[cfg(test)]
#[path = "../../../../tests/unit/agent-types/interaction/types_test.rs"]
mod tests;
