use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InteractionSource {
    System, // framework generated interaction with user
    Tool {
        tool_name: String,
    }, // interaction generated by a tool execution
    Hooker {
        hooker_name: String,
        hook_point: String,
    }, // interaction generated by a hooker
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InteractionRequest {
    Confirm {
        prompt: String,
        source: Option<InteractionSource>,
    },
    TextInput {
        prompt: String,
        source: Option<InteractionSource>,
        #[serde(default)]
        is_secret: bool,
    },
    Choice {
        prompt: String,
        options: Vec<String>,
        allow_custom_input: bool,
        source: Option<InteractionSource>,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum InteractionResponse {
    Confirmed {
        allowed: bool,
    },
    Text {
        value: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        display_value: Option<String>,
    },
    Choice {
        value: Option<String>,
    },
}
