use crate::config_schema::CONFIG_SCHEMA_VERSION;
use xiaoo_shared::daemon_protocol::response::{ManagementCapabilities, ManagementDomainCapability};

pub fn management_capabilities() -> ManagementCapabilities {
    ManagementCapabilities {
        api_version: 1,
        config_schema_version: CONFIG_SCHEMA_VERSION,
        config_commands: [
            "config schema",
            "config providers",
            "config validate",
            "config inspect",
            "config test-model",
            "config models",
            "config roles",
            "config agents",
            "config test-agent",
            "config tools",
            "config custom-tools",
            "config render-custom-tool",
            "config test-custom-tool",
            "config skills",
            "config hooks",
            "config test-hook",
            "config mcp",
            "config mcp-server",
            "config lsp",
            "config install-lsp",
            "config test-lsp",
            "config memory",
            "config memory-queue",
            "config compact",
            "config backend",
            "config channels",
            "config http",
            "config trace",
            "config vault",
            "config set-secret",
            "config delete-secret",
            "config cron",
            "config render-cron",
        ]
        .into_iter()
        .map(str::to_string)
        .collect(),
        domains: vec![
            domain(
                "config",
                true,
                false,
                false,
                true,
                &["schema", "providers", "validate", "inspect"],
            ),
            domain(
                "models",
                true,
                false,
                true,
                true,
                &["session_select", "test_connection", "list_catalog"],
            ),
            domain(
                "agents",
                true,
                false,
                false,
                true,
                &["list", "test_startup"],
            ),
            domain("roles", true, false, false, false, &["list"]),
            domain("subagents", true, false, false, false, &["list_roles"]),
            domain("tools", true, false, false, false, &["list"]),
            domain(
                "custom_tools",
                true,
                true,
                false,
                true,
                &["list", "validate", "render", "test"],
            ),
            domain("skills", true, false, false, false, &["list"]),
            domain(
                "hooks",
                true,
                false,
                true,
                true,
                &["list", "test", "recent_executions"],
            ),
            domain(
                "mcp_client",
                true,
                true,
                false,
                true,
                &["list", "test_connections"],
            ),
            domain(
                "mcp_server",
                true,
                true,
                false,
                true,
                &["inspect", "preflight"],
            ),
            domain(
                "lsp",
                true,
                true,
                true,
                true,
                &["list", "detect", "install", "test_startup"],
            ),
            domain(
                "memory",
                true,
                true,
                false,
                true,
                &[
                    "inspect",
                    "test_connection",
                    "queue_status",
                    "retry_failed_queue",
                    "clear_failed_queue",
                ],
            ),
            domain("compact", true, true, false, true, &["inspect", "validate"]),
            domain(
                "backend",
                true,
                true,
                false,
                true,
                &["inspect", "preflight"],
            ),
            domain(
                "cron",
                true,
                true,
                true,
                true,
                &["list", "validate", "render", "runtime_status", "run_now"],
            ),
            domain(
                "channels",
                true,
                true,
                false,
                true,
                &["inspect", "preflight", "runtime_status", "test_connection"],
            ),
            domain("http", true, true, false, true, &["inspect", "preflight"]),
            domain(
                "trace",
                true,
                true,
                false,
                true,
                &["inspect", "diagnose", "list_recent"],
            ),
            domain(
                "vault",
                true,
                true,
                true,
                true,
                &[
                    "inspect",
                    "preflight",
                    "list_references",
                    "set",
                    "rotate",
                    "delete",
                ],
            ),
            domain(
                "sessions",
                false,
                false,
                true,
                false,
                &["open", "input", "cancel", "close", "heartbeat", "detach"],
            ),
            domain(
                "checkpoints",
                false,
                true,
                true,
                false,
                &["create", "delete_snapshot", "checkout", "export"],
            ),
            domain(
                "sandboxes",
                true,
                true,
                true,
                false,
                &["list", "pause", "resume", "exec", "read_file", "write_file"],
            ),
        ],
    }
}

fn domain(
    id: &'static str,
    configurable: bool,
    runtime_read: bool,
    runtime_write: bool,
    test: bool,
    actions: &[&'static str],
) -> ManagementDomainCapability {
    ManagementDomainCapability {
        id: id.to_string(),
        configurable,
        runtime_read,
        runtime_write,
        test,
        actions: actions.iter().map(|action| (*action).to_string()).collect(),
    }
}

#[cfg(test)]
#[path = "../../../tests/unit/serverside/management_capabilities_test.rs"]
mod tests;
